[package]
name = "discover-neighbors"
version = "0.1.0"
authors = ["mskalka <michaelskalka@gmail.com>"]

[dependencies]
pnet = "0.10.0"
juju = { path = "/home/michael/Juju/" }
charmhelpers = "0.1.3"
log = "0.3.6"
